create table if not exists public.user_prewarm_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  ig_account_id text,
  mode text not null,
  reason text not null,
  ok boolean not null default true,
  skipped text,
  took_ms int,
  created_at timestamptz not null default now()
);

create index if not exists user_prewarm_events_user_created_idx
  on public.user_prewarm_events (user_id, created_at desc);

create index if not exists user_prewarm_events_user_account_created_idx
  on public.user_prewarm_events (user_id, ig_account_id, created_at desc);

alter table public.user_prewarm_events enable row level security;

drop policy if exists "read own prewarm events" on public.user_prewarm_events;
create policy "read own prewarm events"
on public.user_prewarm_events
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "service role insert prewarm events" on public.user_prewarm_events;
create policy "service role insert prewarm events"
on public.user_prewarm_events
for insert
to service_role
with check (true);
